title: Emre Aslan
description: "my personal blog"
author:
  name: "Emre Aslan"
  email: "emreaslanreal@hotmail.com"
  url: "twitter.com/aslanewre"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Emre ASLAN"
year : "2020"
